# Generated by Django 3.2.12 on 2022-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='naomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('file', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('qn', models.CharField(default=0, max_length=5)),
            ],
        ),
    ]
