# Generated by Django 3.2.12 on 2022-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naomi',
            name='file',
        ),
        migrations.RemoveField(
            model_name='naomi',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='naomi',
            name='username',
        ),
        migrations.AddField(
            model_name='naomi',
            name='uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='naomi',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naomi',
            name='qn',
            field=models.IntegerField(default=0),
        ),
    ]
