# Generated by Django 3.2.12 on 2022-03-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='uid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
