# Generated by Django 3.2.12 on 2022-03-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_rank_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rank',
            new_name='ranks',
        ),
    ]
