# Generated by Django 3.2.12 on 2022-03-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_delete_ranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ranks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
