# Generated by Django 3.2.12 on 2022-03-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_ranks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ranks',
            new_name='rank',
        ),
    ]
